version: v2

global:
  runner:
    os_image: ubuntu
  variables:
    - RACK_ENV=test

tasks:
  build-docker-image:
    steps:
      - checkout
      - docker/build:
          image: sravanibikkina/pythoncicd
          dockerfile: Dockerfile
          context: .

  run-docker-container:
    steps:
      - checkout
      - docker/run:
          image: sravanibikkina/pythoncicd
          command: ["python", "app.py"]
