version: v2

global:
  runner:
    container:
      - image: pythoncicd

tasks:
  build-image:
    steps:
      - checkout
      - docker/build:
          image: pythoncicd
          dockerfile: Dockerfile
      - docker/push: 
          image: pythoncicd
          tags: ["${CI_COMMIT_SHA}", "latest"]
      - reports/html:
          dir: coverage
          index: index.html

  deploy:
    when: branch == 'master'
