version: v2

global:
  runner:
    container:
      - image: python:3.8-slim

tasks:
  build-image:
    steps:
      - checkout
      - docker/build:
          image: pythoncicd
          push: true
          tags: ["${CI_COMMIT_SHA}", "latest"]
          dockerfile: Dockerfile
      - reports/html:
          dir: coverage
          index: index.html

  deploy:
    when: branch == 'master'
