version: v2

global:
  runner:
    container:
      - image: pythoncicd

tasks:
  build-image:
    steps:
      - checkout
      - docker/build:
          image: pythoncicd
          dockerfile: Dockerfile
      - docker/push: 
          image: pythoncicd
      - reports/html: 
        dir: htmlcov

  deploy:
    when: branch == 'master'
